apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - infra.minikube.io
      #secretName: tls-certificate
  rules:
  - host: infra.minikube.io
  - http:
      paths:
        - path: /web-application1
          backend:
            serviceName: web1-service
            servicePort: 80
        - path: /web-application2
          backend:
            serviceName: web2-service
            servicePort: 80
